export const LOGIN_USER = "LOGIN_USER";

// OPERATIONS
export const ADD_DONOR = "ADD_DONOR";
export const ADD_LOCATION = "ADD_LOCATION";
export const GET_DONOR = "GET_DONOR";
export const GET_LOCATION = "GET_LOCATION";
export const ADD_VENDOR = "ADD_VENDOR";
export const GET_VENDOR = "GET_VENDOR";

// PROGRAMS
export const ADD_PROGRAM_SUMMARY = "ADD_PROGRAM_SUMMARY";
export const ADD_PROGRAMMATIC_APPROACH = "ADD_PROGRAMMATIC_APPROACH";
export const ADD_MANAGEMENT_APPROACH = "ADD_MANAGEMENT_APPROACH";
export const ADD_PROGRAM_MILESTONES = "ADD_PROGRAM_MILESTONES";
export const ADD_PROGRAM_INDICATORS = "ADD_PROGRAM_INDICATORS";
export const GET_ALL_PROGRAMS = "GET_ALL_PROGRAMS";
export const GET_FORM_DATA_PROGRAMS = "GET_FORM_DATA_PROGRAMS";

// PROJECTS
export const GET_ALL_PROJECTS = "GET_ALL_PROJECTS";
export const ADD_PROJECT_SUMMARY = "ADD_PROJECT_SUMMARY";
export const ADD_PROJECT_WORK_PLAN = "ADD_PROJECT_WORK_PLAN";
export const ADD_PROJECT_SUPPLY = "ADD_PROJECT_SUPPLY";
export const ADD_PROJECT_TEAM = "ADD_PROJECT_TEAM";
export const ADD_PROJECT_MOVEMENT = "ADD_PROJECT_MOVEMENT";
export const ADD_PROJECT_MILESTONES = "ADD_PROJECT_MILESTONES";
export const GET_FORM_DATA_PROJECT = "GET_FORM_DATA_PROJECT";

// options
export const GET_LOCATION_OPTIONS = "GET_LOCATION_OPTIONS";
export const GET_DONOR_OPTIONS = "GET_DONOR_OPTIONS";
export const GET_VENDOR_OPTIONS = "GET_VENDOR_OPTIONS";
export const GET_PROGRAM_OPTIONS = "GET_PROGRAM_OPTIONS";

//Publications
export const ADD_PUBLICATION = "ADD_PUBLICATION";
export const GET_PUBLICATION = "ADD_PUBLICATION";
